# Generated by Django 3.2.25 on 2024-03-29 23:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('obejcts', django.db.models.manager.Manager()),
            ],
        ),
    ]
