# Generated by Django 3.2.25 on 2024-07-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_alter_category_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
    ]
